openapi: 3.2.0
info:
  title: Pipeline Management API v2 Snapshots API
  description: 'The Pipelines API enables programmatic access and control over

    data processing pipelines.'
  version: 2.17.10
servers:
- url: Use API Lookup for a base URL
security:
- Bearer: []
tags:
- name: Snapshots
paths:
  /v2/pipelines/{pipelineId}/snapshots:
    get:
      description: This endpoint returns a list of the Snapshots associated with a Pipeline, sorted in descending order of time created, limited to the last 7 days and a max of 350 snapshots.
      operationId: listSnapshots
      parameters:
      - description: Identifier for a specific http request. If not present, one should be generated. This header and value should be returned in the http response.
        in: header
        name: X-Request-ID
        schema:
          type: string
      - description: Identifier for all http requests made in service of an incoming http request. If not present, one should be generated. This header and value should be included in all outgoing http requests and should be returned in the response.
        in: header
        name: X-Correlation-ID
        schema:
          type: string
      - in: header
        name: Authorization
        schema:
          type: string
      - in: header
        name: Authorization-Claims
        schema:
          type: string
      - description: System generated identifier (UUID or HRN) for the Pipeline.
        examples:
          hrn:
            description: hrn
            summary: pipelineId in HRN format
            value: hrn:here:pipeline::olp-here:00000000-0000-0000-0000-000000000000
          uuid:
            description: uuid
            summary: pipelineId in UUID format
            value: 00000000-0000-0000-0000-000000000000
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
      responses:
        '201':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Snapshot'
                type: array
          description: List retrieved successfully.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Pipeline with provided id not found.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Internal error while retrieving the list of Snapshots.
      summary: List Snapshots of a Pipeline
      tags:
      - Snapshots
  /v2/pipelines/{pipelineId}/snapshots/{snapshotId}:
    get:
      description: This endpoint returns the details about the Snapshot identified by the snapshotId path parameter.
      operationId: getSnapshot
      parameters:
      - description: Identifier for a specific http request. If not present, one should be generated. This header and value should be returned in the http response.
        in: header
        name: X-Request-ID
        schema:
          type: string
      - description: Identifier for all http requests made in service of an incoming http request. If not present, one should be generated. This header and value should be included in all outgoing http requests and should be returned in the response.
        in: header
        name: X-Correlation-ID
        schema:
          type: string
      - in: header
        name: Authorization
        schema:
          type: string
      - in: header
        name: Authorization-Claims
        schema:
          type: string
      - description: System generated identifier (UUID or HRN) for the Pipeline.
        examples:
          hrn:
            description: hrn
            summary: pipelineId in HRN format
            value: hrn:here:pipeline::olp-here:00000000-0000-0000-0000-000000000000
          uuid:
            description: uuid
            summary: pipelineId in UUID format
            value: 00000000-0000-0000-0000-000000000000
        in: path
        name: pipelineId
        required: true
        schema:
          type: string
      - description: System generated identifier (UUID) for the Snapshot.
        in: path
        name: snapshotId
        required: true
        schema:
          format: uuid
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Snapshot'
          description: Snapshot retrieved successfully.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Snapshot with provided id not found.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Internal error while retrieving the Snapshot.
      summary: Get a Snapshot
      tags:
      - Snapshots
components:
  schemas:
    ValidationErrorMessage:
      description: Extends ErrorMessage to add a JSON pointer field and invalid value to the message
      properties:
        code:
          description: Error code that pertains to a specific error.This field will only be populated in the event of known errors. Some errors like field validation may not be able to be done in a reproducible way so it may be omitted in these cases
          example: E1000
          readOnly: true
          type: string
        errors:
          description: Set of validation error messages.
          items:
            $ref: '#/components/schemas/ValidationErrorMessage'
          readOnly: true
          type: array
          uniqueItems: true
        field:
          description: Field of the object that is invalid. The field follows RFC 6901 JSON pointer.
          example: /parent/list/1/value
          externalDocs:
            url: https://tools.ietf.org/html/rfc6901
          readOnly: true
          type: string
        invalidValue:
          description: The invalid value that was sent
          example: sample string
          readOnly: true
          type: object
        message:
          description: This is the message for the error.
          example: Validation Failed
          readOnly: true
          type: string
        messageTemplate:
          description: Message template key that is used to look up a template for localization support. The curly brackets are utilized for looking up the property to get the message. If there are no curly brackets, then the message does not have a template key.
          example: '{validation.error}'
          readOnly: true
          type: string
        status:
          description: Duplicate of the HTTP status that is returned. Where possible utilize the HTTP status. This one is here for convenience.
          example: 400
          format: int32
          readOnly: true
          type: integer
        templateOptions:
          additionalProperties:
            description: Key -> value map of options to be used in a template. This can be passed in for localization to insert in values. A localized template that uses these may look like "The value must be larger than {exampleKey}" where {exampleKey} is replaced with a value for "exampleKey" from the returned map.
            readOnly: true
            type: object
          description: Key -> value map of options to be used in a template. This can be passed in for localization to insert in values. A localized template that uses these may look like "The value must be larger than {exampleKey}" where {exampleKey} is replaced with a value for "exampleKey" from the returned map.
          readOnly: true
          type: object
      readOnly: true
      type: object
    Snapshot:
      description: Snapshot for a Pipeline.
      properties:
        created:
          description: Time and Date when the snapshot was created. This is in ISO-8601 calendar system.
          example: '2007-12-03T10:15:30+01:00'
          format: date-time
          readOnly: true
          type: string
        id:
          description: System generated identifier (UUID) for this object.
          example: 00112233-4455-6677-8899-aabbccddeeff
          format: uuid
          readOnly: true
          type: string
        jobId:
          description: System generated identifier (UUID) for the Job associated with this snapshot.
          example: 00112233-4455-6677-8899-aabbccddeeff
          format: uuid
          type: string
        pipelineId:
          description: System generated identifier (UUID) for the Pipeline associated with this snapshot.
          example: 00112233-4455-6677-8899-aabbccddeeff
          format: uuid
          type: string
        pipelineVersionId:
          description: System generated identifier (UUID) for the PipelineVersion associated with this snapshot.
          example: 00112233-4455-6677-8899-aabbccddeeff
          format: uuid
          type: string
        region:
          description: Region where snapshot was taken.
          type: string
        templateId:
          description: System generated identifier (UUID) for the PipelineTemplate associated with this snapshot.
          example: 00112233-4455-6677-8899-aabbccddeeff
          format: uuid
          type: string
        templateVersionId:
          description: System generated identifier for the PipelineTemplateVersion associated with this snapshot, if applicable.
          example: '1'
          type: string
      required:
      - created
      - jobId
      - pipelineId
      - pipelineVersionId
      - templateId
      type: object
    ErrorMessage:
      type: object
      properties:
        status:
          type: integer
          description: Duplicate of the HTTP status that is returned.
          format: int32
          readOnly: true
          example: 400
        code:
          type: string
          description: Error code that pertains to a specific error.
          readOnly: true
          example: E1000
        message:
          type: string
          description: This is the message for the error.
          readOnly: true
          example: Validation Failed
        messageTemplate:
          type: string
          description: Message template key that is used to look up a template for localization support. The curly brackets are utilized for looking up the property to get the message. If there are no curly brackets, then the message does not have a template key.
          readOnly: true
          example: '{validation.error}'
        templateOptions:
          type: object
          additionalProperties:
            type: object
            properties: {}
          description: Key -> value map of options to be used in a template. This can be passed in for localization to insert in values. A localized template that uses these may look like "The value must be larger than {exampleKey}" where {exampleKey} is replaced with a value for "exampleKey" from the returned map.
          readOnly: true
        errors:
          uniqueItems: true
          type: array
          description: Set of validation error messages.
          readOnly: true
          items:
            $ref: '#/components/schemas/ValidationErrorMessage'
      description: HTTP Error message thrown by the service
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: A token obtained from a separate endpoint using client credentials and an OAuth 1.0a HMAC-SHA256 signed request. For more information on how to get a bearer token, see https://developer.here.com/documentation/identity-access-management/dev_guide/index.html.
externalDocs:
  description: The developer guide and changelogs are available here.
  url: https://www.here.com/docs/category/pipelines-api
